const data=[
  {
    id:1,
    title:"Web Challenge",
    desc:"Here you will get a sample UI of a web page and you have to replicate that web page in a given interval of time.The winners will be selected on the basis of the accuracy of their web page.",
    poster:"images/web.png",
    incharge:["1: Harsh Dubey","2:"],
    volunteers:["1. Vishwa Dev Pratap Singh",
    "2. Shorya Chaturvedi",
    "3. Sonu Kumar",
    "4. Anshu Mishra",
    "5. Ishita Yadav "],
    faculty:["1. Ms. Sana Afreen",
            "2. Ms. Sarika Singh"],
      winners:["1.(Yet To Announce)","2.(Yet To Announce)","3.(Yet To Announce)"],
      phone:"tel:9517229130",
      date:"20th Sept",
      time:"9:00 AM",
      location:" ",

  },
  {
    id:2,
    title:"Treasure Hunt",
    desc:"An exciting sport in which teams will be from every department , where students will be decoding some clues which will lead them to other clues and finally to the end of the game and team finishing the game first will be considered as winner.",
    poster:"images/tressure.jpg",
    incharge:["1: Shivansh Khare","2:"],
    volunteers:["1. Akash Singh ",
    "2. Abu Bakar ",
    "3. Sahil Kumar ",
    "4. Deepankan Srivastava ",
    "5. Rajat Srivastava ",],
    faculty:["1. Ms. Archana Dwivedi",
    "2. Ms. Saumya Singh"],
    winners:["1.(Yet To Announce)","2.(Yet To Announce)","3.(Yet To Announce)"],
      phone:"tel:8887988958",
      date:" ",
      time:" ",
      location:" ",

  },
  {
    id:3,
    title:"Mock Interview",
    desc:"Here you all have to face some random Questions, the same as in a real interview. There will be multiple rounds of mock interviews and some selected students are qualified for the final round. The winner will be announced based on their overall performance.",
    poster:"images/mock interview.jpg",
    incharge:["1: Jaya Khare","2:"],
    volunteers:[
    "1. Swapnil Verma ",
    "2. Tushika Srivastava "],
    faculty:["1. Mrs. Apporva Mishra", "2. Ms. Arpita Srivastava"],
    winners:["1.(Yet To Announce)","2.(Yet To Announce)","3.(Yet To Announce)"],
      phone:"tel:6392004353",
      date:" ",
      time:" ",
      location:" ",

  },
  {
    id:4,
    title:"Coding Contest",
    desc:"Some coding problems will be provided to you. You have to solve that problem in the given timespan. The winner will be announced according to their points.",
    poster:"images/coding.jpg",
    incharge:["1: Sudeep Jaiswal","2:"],
    volunteers:["1. Alok Pal ",
      "2. Rishabh Mishra",
      "3. Ajeet Kumar",
      "4. Manoj Pandey ",
      "5. Ankit Kumar Maurya "],
    faculty:[
            "1. Mrs. Akanksha Srivastava"],
            winners:["1.(Yet To Announce)","2.(Yet To Announce)","3.(Yet To Announce)"],
      phone:"tel:8726776286",
      date:" ",
      time:" ",
      location:" ",

  },
  {
    id:5,
    title:"Aptitude & Technical Quiz",
    desc:"A multiple choice questions quiz based on technical subjects and aptitude.",
    poster:"images/tech quiz.jpg",
    incharge:["1: Nisha Kumari","2:"],
    volunteers:["1.Sneha Singh Pal",
     " 2.Navya Yadav ",
      "3.Ujjwal Srivastava ",
      "4.Shaswat Chauhan ",
      "5.Sujeet Kumar Sahu "],
    faculty:["1. Mr. Ashish Mishra",
      "2. Mr. Nirupma Pathak"],
      winners:["1.(Yet To Announce)","2.(Yet To Announce)","3.(Yet To Announce)"],
      phone:"tel:7979962585",
      date:" ",
      time:" ",
      location:" ",
  },
  {
    id:6,
    title:"Nexxplora Shine",
    desc:"In this contest, you can showcase your extra curricular activities like SINGING, POETRY, STAND UP COMEDY, etc. You will be performing in front of judges, and winners will be selected by the total marks based on your performance.",
    poster:"images/shine.jpg",
    incharge:["1: Mansi jain","2:"],
    volunteers:["1. Harsh Vardhan Singh",
     " 2. Monika Patel ",
     " 3. Gauri Mishra ",
     " 4. Aryanshi Singh ",
      " 5. Sandhya Maddhesiya "],
    faculty:["1. Mr. Ram Dubey",
      "2. Mr. Anurag Singh"],
      winners:["1.(Yet To Announce)","2.(Yet To Announce)","3.(Yet To Announce)"],
      phone:"tel:9557020393",
      date:" ",
      time:" ",
      location:" ",
  },
  {
    id:7,
    title:"Arm wrestling",
    desc:"An arm wrestling competition. Why bother about brains when you can test out your strength !",
    poster:"images/arm.jpg",
    incharge:["1: Akhilendra Mishra","2:"],
    volunteers:["1. Udit Srivastava ",
    "2. Mukul Singh"],
    faculty:["1. Mr. Sumit Yadav",
            "2. Mr. Anoop Mathur"],
            winners:["1.(Yet To Announce)","2.(Yet To Announce)","3.(Yet To Announce)"],
      phone:"tel:6386068129",
      date:" ",
      time:" ",
      location:" ",

  },
  {
    id:8,
    title:"BGMI",
    desc:"A series of custom games for the BGMI enthusiasts.",
    poster:"images/bgmi.jpg",
    incharge:["1: Rishabh Singh","2:"],
    volunteers:["1.Shivendra Srivastava",
    "2.Harsh Dubey"],
    faculty:["1. Mr. Sumit Yadav",
            "2. Mr. Anoop Mathur"],
            winners:["1.(Yet To Announce)","2.(Yet To Announce)","3.(Yet To Announce)"],
      phone:"tel:6393411553",
      date:" ",
      time:" ",
      location:" ",

  },
  {
    id:9,
    desc:"A LAN tournament of Need For Speed Most Wanted , laptops will be provided.",
    title:"Need For Speed",
    poster:"images/NFSS.jpg",
    incharge:["1:Ajay Tandon","2:"],
    volunteers:["1. Pawan Kumar Singh ",
    "2. Shubham Shukla"],
   faculty:["1. Mr. Sumit Yadav",
            "2. Mr. Anoop Mathur"],
            winners:["1.(Yet To Announce)","2.(Yet To Announce)","3.(Yet To Announce)"],
      phone:"tel:7651893649",
      date:" ",
      time:" ",
      location:" ",

  },
  {
    id:10,
    desc:"This is a poster making competition for all the creative folks out there , design a poster and win it all.",
    title:"Poster making",
    poster:"images/poster making.jpg",
    incharge:["1: Farhan","2:"],
    volunteers:[
    "1. Harsh Mishra",
    "2. Pragya Singh"],
    faculty:["1. Mr. Dushyant Srivastava",
            "2. Ms. Deepti Rajdan"],
            winners:["1.(Yet To Announce)","2.(Yet To Announce)","3.(Yet To Announce)"],
      phone:"tel:6392182441",
      date:" ",
      time:" ",
      location:" ",

  },
  {
    id:11,
    desc:"In this program, you have to present any project or idea you have built or thought about. You have to make a PowerPoint presentation on it and should present it in front of all. Winners will be selected on the basis of the uniqueness and originality of ideas and your presentation skills. Make sure to not copy the idea from somewhere else.",
    title:"Project Presentation",
    poster:"images/presentation.jpeg",
    incharge:["1: Bhumika Srivastava","2:"],
    volunteers:[
    "1. Km. Anshula ",
    "2. Gopal Tiwari",
    "3. Harsh Barnawal "],
    faculty:["1.Mr. Saif Zaheer"],
    winners:["1.(Yet To Announce)","2.(Yet To Announce)","3.(Yet To Announce)"],
      phone:"tel:8795438658",
      date:" ",
      time:" ",
      location:" ",

  },
  {
    id:12,
    desc:"Here you will get a topic on the spot , and you have to speak on that topic.",
    title:"Extempore",
    poster:"images/extempore.png",
    incharge:["1: Babita Pandey","2:"],
    volunteers:[
    "1. Deepa Sen Nirala ",
    "2. Poornima Singh "],
      faculty:["1. Mrs. Apporva Mishra", "2. Ms. Arpita Srivastava"],
      winners:["1.(Yet To Announce)","2.(Yet To Announce)","3.(Yet To Announce)"],
      phone:"tel:9125958225",
      date:" ",
      time:" ",
      location:" ",
  },
  {
    id:13,
    desc:"This is complete replication of a real world interview process , it contains an aptitude round followed by a quiz on programming and finally a technical interview for which you should carry your resume with yourself.",
    title:"Placed",
    poster:"images/placenewww.jpg",
    incharge:["1: Prakhar Saxena","2: Neelesh Prajapati"],
    volunteers:[
    "1. Devansh Singh",
    "2. Shweta Yadav "],
    faculty:["1. Mr. Sambhav Agarwal",
            "2. Mr. Rahul Gupta",
            "3. Mr. Dushyant Srivastava",
            "4. Mr. Sanjay Tandon"],
            winners:["1.(Yet To Announce)","2.(Yet To Announce)","3.(Yet To Announce)"],
      phone:"tel:8954535590",
      date:" ",
      time:" ",
      location:" ",
  },

];

export default data;